services:
  - type: web
    name: image-to-text-converter
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      apt-get install -y tesseract-ocr-vie
      apt-get install -y libtesseract-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: PYTHONPATH
        value: /opt/render/project/src
